# Generated by Django 5.2 on 2025-04-13 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('date_filter', models.DateField(blank=True, null=True)),
                ('sync_all', models.BooleanField(default=False)),
                ('new_events_count', models.PositiveIntegerField(default=0)),
                ('updated_events_count', models.PositiveIntegerField(default=0)),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Результат синхронизации',
                'verbose_name_plural': 'Результаты синхронизации',
                'ordering': ['-started_at'],
            },
        ),
    ]
