[project]
name = "events-face"
version = "0.1.0"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[build-system]
requires = ["uv"]
build-backend = "uv.core.build"